#!/usr/bin/env python3
"""
Generates a ready-to-use .env file for FabriQ.

Usage:
    python scripts/init_env.py

The script asks for email, password, tenant_id and role,
then writes .env at the project root with a generated JWT secret
and the bcrypt hash of the password.
"""
import os
import secrets
import sys


def main() -> None:
    try:
        import bcrypt
    except ImportError:
        print("bcrypt not installed. Run: pip install bcrypt")
        sys.exit(1)

    print("=== FabriQ — initialisation de l'environnement ===\n")

    email = input("Email de l'administrateur [admin@fabriq.io]: ").strip() or "admin@fabriq.io"
    password = input("Mot de passe: ").strip()
    if not password:
        print("Le mot de passe ne peut pas être vide.")
        sys.exit(1)
    tenant_id = input("Tenant ID [tenant_demo]: ").strip() or "tenant_demo"
    role = input("Rôle (admin/viewer) [admin]: ").strip() or "admin"

    hashed = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt(rounds=12)).decode("utf-8")
    jwt_secret = secrets.token_hex(32)

    db_password = input("\nMot de passe DB read-only [fabriq_readonly]: ").strip() or "fabriq_readonly"

    env_content = f"""# Generated by scripts/init_env.py
# ─── Database ─────────────────────────────────────────────────────────────────
FABRIQ_DB_READONLY_PASSWORD={db_password}
FABRIQ_DATABASE_URL=postgresql://fabriq_readonly:{db_password}@127.0.0.1:5432/fabriq

# ─── LLM (optional) ───────────────────────────────────────────────────────────
FABRIQ_LLM_PROVIDER=disabled
FABRIQ_OLLAMA_URL=http://127.0.0.1:11434
FABRIQ_OLLAMA_MODEL=llama3.1
FABRIQ_LLM_TIMEOUT_SECONDS=60

# ─── Auth JWT ─────────────────────────────────────────────────────────────────
FABRIQ_JWT_SECRET={jwt_secret}
FABRIQ_JWT_EXPIRE_MINUTES=60
# Format: email:bcrypt_hash:tenant_id:role
FABRIQ_USERS={email}:{hashed}:{tenant_id}:{role}
"""

    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    env_path = os.path.normpath(env_path)

    if os.path.exists(env_path):
        overwrite = input(f"\n.env existe déjà ({env_path}). Écraser ? (o/N): ").strip().lower()
        if overwrite != "o":
            print("Annulé.")
            sys.exit(0)

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    print(f"\n✓ .env généré : {env_path}")
    print(f"  Utilisateur  : {email} ({role}, tenant={tenant_id})")
    print("  JWT secret   : (généré aléatoirement)")
    print("\nPour démarrer :")
    print("  docker-compose up --build")
    print("  # ou localement :")
    print("  cd backend && uvicorn app.main:app --reload")


if __name__ == "__main__":
    main()
